language: generic

os:
  - linux
  - osx

sudo: false

env:
  global:
    - FISH_RELEASE="http://fishshell.com/files/2.2.0/fish-2.2.0.tar.gz"
    - OMF_INSTALLER="https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
    - NVM_INSTALLER="https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh"

install:
  - ./.install-$TRAVIS_OS_NAME.sh

cache:
  directories:
    - $HOME/fish
    - $HOME/.nvm
    - $HOME/.config
    - $HOME/.local

script:
  - PATH=$HOME/fish/bin:$PATH fish test/bootstrap.fish
