language: generic

matrix:
  include:
    - os: osx
      env:
        - FISH_STRATEGY=homebrew
        - NVM_STRATEGY=homebrew
    - os: osx
      env:
        - FISH_STRATEGY=homebrew
        - NVM_STRATEGY=official
    - os: linux
      env:
        - FISH_STRATEGY=source
        - NVM_STRATEGY=official

sudo: false

env:
  global:
    - FISH_RELEASE="http://fishshell.com/files/2.2.0/fish-2.2.0.tar.gz"
    - OMF_INSTALLER="https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
    - NVM_INSTALLER="https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh"
    - PATH=$HOME/fish/bin:$PATH

install:
  - ./.fish-install-$FISH_STRATEGY.sh
  - ./.nvm-install-$NVM_STRATEGY.sh
  - ./.omf-install.sh
  - ./.plugin-install.sh

cache:
  directories:
    - $HOME/fish
    - $HOME/.nvm
    - $HOME/.config
    - $HOME/.local

script:
  - fish test/bootstrap.fish
